// Six faces, each with nominally 240 leds, actual numbers vary slightly
#define NUM_LEDS_FACE_ONE 238 	// tested & accurate 	// red in testing mode 3
#define NUM_LEDS_FACE_TWO 237 	// tested & accurate	// green in testing mode 3
#define NUM_LEDS_FACE_THREE 237 // tested & accurate	// blue in testing mode 3
#define NUM_LEDS_FACE_FOUR 237 	// tested & accurate	// yellow in testing mode 3
#define NUM_LEDS_FACE_FIVE 232 	// tested & accurate	// aqua in testing mode 3
#define NUM_LEDS_FACE_SIX 233 	// tested & accurate	// aquamarine in testing mode 3

// It's helpful to know which set of leds are on which face AND side

// should add up to NUM_LEDS_FACE_ONE (238)
#define NUM_LEDS_FACE_ONE_SIDE_ONE 58
#define NUM_LEDS_FACE_ONE_SIDE_TWO 60
#define NUM_LEDS_FACE_ONE_SIDE_THREE 60
#define NUM_LEDS_FACE_ONE_SIDE_FOUR 60

#define FACE_ONE_SIDE_ONE_START 0
#define FACE_ONE_SIDE_ONE_END NUM_LEDS_FACE_ONE_SIDE_ONE - 1

#define FACE_ONE_SIDE_TWO_START NUM_LEDS_FACE_ONE_SIDE_ONE
#define FACE_ONE_SIDE_TWO_END FACE_ONE_SIDE_TWO_START + NUM_LEDS_FACE_ONE_SIDE_TWO - 1

#define FACE_ONE_SIDE_THREE_START NUM_LEDS_FACE_ONE_SIDE_ONE + NUM_LEDS_FACE_ONE_SIDE_TWO
#define FACE_ONE_SIDE_THREE_END FACE_ONE_SIDE_THREE_START + NUM_LEDS_FACE_ONE_SIDE_THREE - 1

#define FACE_ONE_SIDE_FOUR_START NUM_LEDS_FACE_ONE_SIDE_ONE + NUM_LEDS_FACE_ONE_SIDE_TWO + NUM_LEDS_FACE_ONE_SIDE_THREE
#define FACE_ONE_SIDE_FOUR_END FACE_ONE_SIDE_FOUR_START + NUM_LEDS_FACE_ONE_SIDE_FOUR - 1

// should add up to NUM_LEDS_FACE_TWO (237)
#define NUM_LEDS_FACE_TWO_SIDE_ONE 59
#define NUM_LEDS_FACE_TWO_SIDE_TWO 60
#define NUM_LEDS_FACE_TWO_SIDE_THREE 59
#define NUM_LEDS_FACE_TWO_SIDE_FOUR 59

#define FACE_TWO_SIDE_ONE_START 0
#define FACE_TWO_SIDE_ONE_END NUM_LEDS_FACE_TWO_SIDE_ONE - 1

#define FACE_TWO_SIDE_TWO_START NUM_LEDS_FACE_TWO_SIDE_ONE
#define FACE_TWO_SIDE_TWO_END FACE_TWO_SIDE_TWO_START + NUM_LEDS_FACE_TWO_SIDE_TWO - 1

#define FACE_TWO_SIDE_THREE_START NUM_LEDS_FACE_TWO_SIDE_ONE + NUM_LEDS_FACE_TWO_SIDE_TWO
#define FACE_TWO_SIDE_THREE_END FACE_TWO_SIDE_THREE_START + NUM_LEDS_FACE_TWO_SIDE_THREE - 1

#define FACE_TWO_SIDE_FOUR_START NUM_LEDS_FACE_TWO_SIDE_ONE + NUM_LEDS_FACE_TWO_SIDE_TWO + NUM_LEDS_FACE_TWO_SIDE_THREE
#define FACE_TWO_SIDE_FOUR_END FACE_TWO_SIDE_FOUR_START + NUM_LEDS_FACE_TWO_SIDE_FOUR - 1

// should add up to NUM_LEDS_FACE_THREE (237)
#define NUM_LEDS_FACE_THREE_SIDE_ONE 57
#define NUM_LEDS_FACE_THREE_SIDE_TWO 60
#define NUM_LEDS_FACE_THREE_SIDE_THREE 60
#define NUM_LEDS_FACE_THREE_SIDE_FOUR 60

#define FACE_THREE_SIDE_ONE_START 0
#define FACE_THREE_SIDE_ONE_END NUM_LEDS_FACE_THREE_SIDE_ONE - 1

#define FACE_THREE_SIDE_TWO_START NUM_LEDS_FACE_THREE_SIDE_ONE
#define FACE_THREE_SIDE_TWO_END FACE_THREE_SIDE_TWO_START + NUM_LEDS_FACE_THREE_SIDE_TWO - 1

#define FACE_THREE_SIDE_THREE_START NUM_LEDS_FACE_THREE_SIDE_ONE + NUM_LEDS_FACE_THREE_SIDE_TWO
#define FACE_THREE_SIDE_THREE_END FACE_THREE_SIDE_THREE_START + NUM_LEDS_FACE_THREE_SIDE_THREE - 1

#define FACE_THREE_SIDE_FOUR_START NUM_LEDS_FACE_THREE_SIDE_ONE + NUM_LEDS_FACE_THREE_SIDE_TWO + NUM_LEDS_FACE_THREE_SIDE_THREE
#define FACE_THREE_SIDE_FOUR_END FACE_THREE_SIDE_FOUR_START + NUM_LEDS_FACE_THREE_SIDE_FOUR - 1

// should add up to NUM_LEDS_FACE_FOUR (237)
#define NUM_LEDS_FACE_FOUR_SIDE_ONE 58
#define NUM_LEDS_FACE_FOUR_SIDE_TWO 60
#define NUM_LEDS_FACE_FOUR_SIDE_THREE 60
#define NUM_LEDS_FACE_FOUR_SIDE_FOUR 59

#define FACE_FOUR_SIDE_ONE_START 0
#define FACE_FOUR_SIDE_ONE_END NUM_LEDS_FACE_FOUR_SIDE_ONE - 1

#define FACE_FOUR_SIDE_TWO_START NUM_LEDS_FACE_FOUR_SIDE_ONE
#define FACE_FOUR_SIDE_TWO_END FACE_FOUR_SIDE_TWO_START + NUM_LEDS_FACE_FOUR_SIDE_TWO - 1

#define FACE_FOUR_SIDE_THREE_START NUM_LEDS_FACE_FOUR_SIDE_ONE + NUM_LEDS_FACE_FOUR_SIDE_TWO
#define FACE_FOUR_SIDE_THREE_END FACE_FOUR_SIDE_THREE_START + NUM_LEDS_FACE_FOUR_SIDE_THREE - 1

#define FACE_FOUR_SIDE_FOUR_START NUM_LEDS_FACE_FOUR_SIDE_ONE + NUM_LEDS_FACE_FOUR_SIDE_TWO + NUM_LEDS_FACE_FOUR_SIDE_THREE
#define FACE_FOUR_SIDE_FOUR_END FACE_FOUR_SIDE_FOUR_START + NUM_LEDS_FACE_FOUR_SIDE_FOUR - 1

// should add up to NUM_LEDS_FACE_FIVE (232)
#define NUM_LEDS_FACE_FIVE_SIDE_ONE 57
#define NUM_LEDS_FACE_FIVE_SIDE_TWO 59
#define NUM_LEDS_FACE_FIVE_SIDE_THREE 58
#define NUM_LEDS_FACE_FIVE_SIDE_FOUR 58

#define FACE_FIVE_SIDE_ONE_START 0
#define FACE_FIVE_SIDE_ONE_END NUM_LEDS_FACE_FIVE_SIDE_ONE - 1

#define FACE_FIVE_SIDE_TWO_START NUM_LEDS_FACE_FIVE_SIDE_ONE
#define FACE_FIVE_SIDE_TWO_END FACE_FIVE_SIDE_TWO_START + NUM_LEDS_FACE_FIVE_SIDE_TWO - 1

#define FACE_FIVE_SIDE_THREE_START NUM_LEDS_FACE_FIVE_SIDE_ONE + NUM_LEDS_FACE_FIVE_SIDE_TWO
#define FACE_FIVE_SIDE_THREE_END FACE_FIVE_SIDE_THREE_START + NUM_LEDS_FACE_FIVE_SIDE_THREE - 1

#define FACE_FIVE_SIDE_FOUR_START NUM_LEDS_FACE_FIVE_SIDE_ONE + NUM_LEDS_FACE_FIVE_SIDE_TWO + NUM_LEDS_FACE_FIVE_SIDE_THREE
#define FACE_FIVE_SIDE_FOUR_END FACE_FIVE_SIDE_FOUR_START + NUM_LEDS_FACE_FIVE_SIDE_FOUR - 1

// should add up to NUM_LEDS_FACE_SIX (233)
#define NUM_LEDS_FACE_SIX_SIDE_ONE 57
#define NUM_LEDS_FACE_SIX_SIDE_TWO 59
#define NUM_LEDS_FACE_SIX_SIDE_THREE 59
#define NUM_LEDS_FACE_SIX_SIDE_FOUR 58

#define FACE_SIX_SIDE_ONE_START 0
#define FACE_SIX_SIDE_ONE_END NUM_LEDS_FACE_SIX_SIDE_ONE - 1

#define FACE_SIX_SIDE_TWO_START NUM_LEDS_FACE_SIX_SIDE_ONE
#define FACE_SIX_SIDE_TWO_END FACE_SIX_SIDE_TWO_START + NUM_LEDS_FACE_SIX_SIDE_TWO - 1

#define FACE_SIX_SIDE_THREE_START NUM_LEDS_FACE_SIX_SIDE_ONE + NUM_LEDS_FACE_SIX_SIDE_TWO
#define FACE_SIX_SIDE_THREE_END FACE_SIX_SIDE_THREE_START + NUM_LEDS_FACE_SIX_SIDE_THREE - 1

#define FACE_SIX_SIDE_FOUR_START NUM_LEDS_FACE_SIX_SIDE_ONE + NUM_LEDS_FACE_SIX_SIDE_TWO + NUM_LEDS_FACE_SIX_SIDE_THREE
#define FACE_SIX_SIDE_FOUR_END FACE_SIX_SIDE_FOUR_START + NUM_LEDS_FACE_SIX_SIDE_FOUR - 1