// QUICK CHANGE variables
#define NUM_LEDS 134
#define LED_PIN 27
#define CLOCK_PIN 26
#define SERIAL_ENABLED true
#define STARTUP_DEBUG false
#define MAX_BRIGHT 128
#define SERIAL_BAUDRATE 115200
// QUICK CHANGE VARIABLES




// FUNCTION DEFINES
void enableWifi();



// FUNCTION DEFINES