// QUICK CHANGE variables
#define STARTUP_DEBUG false
#define MAX_BRIGHT 128
#define SERIAL_BAUDRATE 115200
// QUICK CHANGE VARIABLES

// HYPERCUBE LED PINS
#define LED_PIN_ONE 2
#define LED_PIN_TWO 3
#define LED_PIN_THREE 4
#define LED_PIN_FOUR 5
#define LED_PIN_FIVE 6
#define LED_PIN_SIX 7

// HYPERCUBE LED COUNTS
